require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PayslipsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Payslip. As you add validations to Payslip, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PayslipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all payslips as @payslips" do
      payslip = Payslip.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:payslips)).to eq([payslip])
    end
  end

  describe "GET #show" do
    it "assigns the requested payslip as @payslip" do
      payslip = Payslip.create! valid_attributes
      get :show, {:id => payslip.to_param}, valid_session
      expect(assigns(:payslip)).to eq(payslip)
    end
  end

  describe "GET #new" do
    it "assigns a new payslip as @payslip" do
      get :new, {}, valid_session
      expect(assigns(:payslip)).to be_a_new(Payslip)
    end
  end

  describe "GET #edit" do
    it "assigns the requested payslip as @payslip" do
      payslip = Payslip.create! valid_attributes
      get :edit, {:id => payslip.to_param}, valid_session
      expect(assigns(:payslip)).to eq(payslip)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Payslip" do
        expect {
          post :create, {:payslip => valid_attributes}, valid_session
        }.to change(Payslip, :count).by(1)
      end

      it "assigns a newly created payslip as @payslip" do
        post :create, {:payslip => valid_attributes}, valid_session
        expect(assigns(:payslip)).to be_a(Payslip)
        expect(assigns(:payslip)).to be_persisted
      end

      it "redirects to the created payslip" do
        post :create, {:payslip => valid_attributes}, valid_session
        expect(response).to redirect_to(Payslip.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved payslip as @payslip" do
        post :create, {:payslip => invalid_attributes}, valid_session
        expect(assigns(:payslip)).to be_a_new(Payslip)
      end

      it "re-renders the 'new' template" do
        post :create, {:payslip => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested payslip" do
        payslip = Payslip.create! valid_attributes
        put :update, {:id => payslip.to_param, :payslip => new_attributes}, valid_session
        payslip.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested payslip as @payslip" do
        payslip = Payslip.create! valid_attributes
        put :update, {:id => payslip.to_param, :payslip => valid_attributes}, valid_session
        expect(assigns(:payslip)).to eq(payslip)
      end

      it "redirects to the payslip" do
        payslip = Payslip.create! valid_attributes
        put :update, {:id => payslip.to_param, :payslip => valid_attributes}, valid_session
        expect(response).to redirect_to(payslip)
      end
    end

    context "with invalid params" do
      it "assigns the payslip as @payslip" do
        payslip = Payslip.create! valid_attributes
        put :update, {:id => payslip.to_param, :payslip => invalid_attributes}, valid_session
        expect(assigns(:payslip)).to eq(payslip)
      end

      it "re-renders the 'edit' template" do
        payslip = Payslip.create! valid_attributes
        put :update, {:id => payslip.to_param, :payslip => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested payslip" do
      payslip = Payslip.create! valid_attributes
      expect {
        delete :destroy, {:id => payslip.to_param}, valid_session
      }.to change(Payslip, :count).by(-1)
    end

    it "redirects to the payslips list" do
      payslip = Payslip.create! valid_attributes
      delete :destroy, {:id => payslip.to_param}, valid_session
      expect(response).to redirect_to(payslips_url)
    end
  end

end
